// src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import "./App.css";  // Global CSS styles; you can add app-wide styles here.
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';  // Generated by sandbox/deploy; contains backend config like API endpoints.
import '@aws-amplify/ui-react/styles.css'; // Import Amplify UI styles for proper component rendering
import { ThemeProvider } from '@aws-amplify/ui-react'; // Use ThemeProvider for theme context

// Configure Amplify to use the backend resources. This enables auth and GraphQL API calls throughout the app.
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider> {/* Wrap the app to enable Amplify UI theme tokens and styles */}
      <App />  
    </ThemeProvider>
  </React.StrictMode>,
);
