// src/main.tsx
// This is the entry point of the React app. It configures Amplify with the backend (via amplify_outputs.json from sandbox/deploy) and renders the root App component.
// Amplify.configure() connects the frontend to AWS services like Auth and API.
// Wrap the app in React StrictMode for development checks, and render to the DOM.

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import './index.css';  // Global CSS styles; you can add app-wide styles here.
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';  // Generated by sandbox/deploy; contains backend config like API endpoints.

// Configure Amplify to use the backend resources. This enables auth and GraphQL API calls throughout the app.
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />  // Renders the main App component, which handles auth and sections.
  </React.StrictMode>,
);
